name: FrostTicTacToe
api: 5.0.0
main: FrostTicTacToe\Main
version: 2.0.0
author: DEVILxD5919

commands:
  tictactoe:
    permission: FrostTicTacToe.cmd
    usage: "/fttt (help|start|list|end|join <playerName>)"
    aliases: ["fttt"]
    
permissions:
  FrostTicTacToe.cmd:
    default: true
